apiVersion: v1
kind: Service
metadata:
  name: test-state-svc
  labels:
    app: test-state-app
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: test-state-app

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-state-ss
spec:
  selector:
    matchLabels:
      app: test-state-app
  serviceName: "test-state-svc"
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-state-app
    spec:
      containers:
        - name: main
          image: nginx
          ports:
            - containerPort: 80
              name: www
          volumeMounts:
            - name: test-state-pvc
              mountPath: "/usr/share/nginx/html"
  volumeClaimTemplates:
    - metadata:
        name: test-state-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: regional-persistent-balanced
        resources:
          requests:
            storage: 1Gi

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   annotations:
#     pv.kubernetes.io/provisioned-by: pd.csi.storage.gke.io
#     volume.kubernetes.io/provisioner-deletion-secret-name: ""
#     volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
#   creationTimestamp: "2023-05-14T10:28:19Z"
#   finalizers:
#     - kubernetes.io/pv-protection
#     - external-attacher/pd-csi-storage-gke-io
#   name: pvc-934eef36-dd92-48f0-b859-adb45a4326e3
#   resourceVersion: "670320"
#   uid: d4e5b97d-aa89-412b-a5af-7705212582e8
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   claimRef:
#     apiVersion: v1
#     kind: PersistentVolumeClaim
#     name: pvc-demo
#     namespace: default
#     resourceVersion: "670272"
#     uid: 934eef36-dd92-48f0-b859-adb45a4326e3
#   csi:
#     driver: pd.csi.storage.gke.io
#     fsType: ext4
#     volumeAttributes:
#       storage.kubernetes.io/csiProvisionerIdentity: 1684054274579-8081-pd.csi.storage.gke.io
#     volumeHandle: projects/polytotem-hq-prod/regions/europe-central2/disks/pvc-934eef36-dd92-48f0-b859-adb45a4326e3
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: topology.gke.io/zone
#               operator: In
#               values:
#                 - europe-central2-a
#         - matchExpressions:
#             - key: topology.gke.io/zone
#               operator: In
#               values:
#                 - europe-central2-b
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: regional-persistent-balanced
#   volumeMode: Filesystem

# ---
# # pvc-pod-demo.yaml
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-demo
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 200Mi
#   storageClassName: regional-persistent-balanced

# ---
# kind: Pod
# apiVersion: v1
# metadata:
#   name: pod-demo
# spec:
#   volumes:
#     - name: pvc-demo-vol
#       persistentVolumeClaim:
#         claimName: pvc-demo
#   containers:
#     - name: pod-demo
#       image: nginx
#       resources:
#         limits:
#           cpu: 10m
#           memory: 80Mi
#         requests:
#           cpu: 10m
#           memory: 80Mi
#       ports:
#         - containerPort: 80
#           name: "http-server"
#       volumeMounts:
#         - mountPath: "/usr/share/nginx/html"
#           name: pvc-demo-vol

# ---
# # pvc-pod-demo.yaml
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-demo-2
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 500Mi
#   storageClassName: regional-persistent-balanced

# ---
# kind: Pod
# apiVersion: v1
# metadata:
#   name: pod-demo-2
# spec:
#   volumes:
#     - name: pvc-demo-2-vol
#       persistentVolumeClaim:
#         claimName: pvc-demo-2
#   containers:
#     - name: pod-demo-2
#       image: nginx
#       resources:
#         limits:
#           cpu: 10m
#           memory: 80Mi
#         requests:
#           cpu: 10m
#           memory: 80Mi
#       ports:
#         - containerPort: 80
#           name: "http-server"
#       volumeMounts:
#         - mountPath: "/usr/share/nginx/html"
#           name: pvc-demo-2-vol
